export interface ContentFormat {
  id: string
  name: string
  platform: string
  category: string
  width: number
  height: number
  aspectRatio: string
  safeZone?: {
    top: number
    bottom: number
    left: number
    right: number
  }
  description: string
  fileTypes: string[]
  maxFileSize?: string
  notes?: string
}

export const categories = [
  { id: "all", name: "All Formats", count: 0 },
  { id: "social-media", name: "Social Media", count: 0 },
  { id: "messaging", name: "Messaging Apps", count: 0 },
  { id: "video", name: "Video Platforms", count: 0 },
  { id: "ecommerce", name: "E-commerce", count: 0 },
  { id: "advertising", name: "Advertising", count: 0 },
  { id: "print", name: "Print & Documents", count: 0 },
  { id: "community", name: "Community Platforms", count: 0 },
  { id: "developer", name: "Developer Tools", count: 0 },
]

export const contentFormats: ContentFormat[] = [
  // ---------- UPDATED / ORIGINAL ENTRIES (validated & corrected) ----------
  {
    id: "instagram-post",
    name: "Instagram Post",
    platform: "Instagram",
    category: "social-media",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    description: "Square format for Instagram feed posts",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "30MB",
    safeZone: { top: 50, bottom: 50, left: 50, right: 50 },
  },
  {
    id: "instagram-story",
    name: "Instagram Story",
    platform: "Instagram",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical format for Instagram Stories and Reels covers",
    fileTypes: ["JPG", "PNG", "MP4", "MOV"],
    maxFileSize: "4GB",
    safeZone: { top: 250, bottom: 250, left: 50, right: 50 },
  },
  {
    id: "tiktok-video",
    name: "TikTok Video",
    platform: "TikTok",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical video format for TikTok",
    fileTypes: ["MP4", "MOV"],
    maxFileSize: "287.6MB",
    safeZone: { top: 200, bottom: 200, left: 50, right: 50 },
  },
  {
    id: "youtube-thumbnail",
    name: "YouTube Thumbnail",
    platform: "YouTube",
    category: "social-media",
    width: 1280,
    height: 720,
    aspectRatio: "16:9",
    description: "Thumbnail image for YouTube videos (min 1280×720 recommended)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "2MB",
    safeZone: { top: 40, bottom: 40, left: 40, right: 40 },
  },
  {
    id: "facebook-post",
    name: "Facebook Post",
    platform: "Facebook",
    category: "social-media",
    width: 1200,
    height: 630,
    aspectRatio: "1.91:1",
    description: "Landscape format for Facebook posts and link previews",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "30MB",
  },
  {
    id: "twitter-post",
    name: "Twitter/X Post",
    platform: "Twitter/X",
    category: "social-media",
    width: 1200,
    height: 675,
    aspectRatio: "16:9",
    description: "Image format for Twitter/X posts (single image)",
    fileTypes: ["JPG", "PNG", "GIF", "WEBP"],
    maxFileSize: "5MB",
  },
  {
    id: "linkedin-post",
    name: "LinkedIn Post",
    platform: "LinkedIn",
    category: "social-media",
    width: 1200,
    height: 627,
    aspectRatio: "1.91:1",
    description: "Professional post image for LinkedIn feed",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "10MB",
  },

  // Messaging Apps (expanded & validated)
  {
    id: "whatsapp-status",
    name: "WhatsApp Status",
    platform: "WhatsApp",
    category: "messaging",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical format for WhatsApp Status updates",
    fileTypes: ["JPG", "PNG", "MP4"],
    maxFileSize: "16MB",
  },
  {
    id: "discord-banner",
    name: "Discord Server Banner",
    platform: "Discord",
    category: "messaging",
    width: 960,
    height: 540,
    aspectRatio: "16:9",
    description: "Banner image for Discord servers (max file size 10MB)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "10MB",
  },
  {
    id: "telegram-sticker",
    name: "Telegram Sticker",
    platform: "Telegram",
    category: "messaging",
    width: 512,
    height: 512,
    aspectRatio: "1:1",
    description: "Square format for Telegram stickers (PNG/WebP)",
    fileTypes: ["PNG", "WEBP"],
    maxFileSize: "512KB",
  },
  {
    id: "wechat-moments",
    name: "WeChat Moments Image",
    platform: "WeChat",
    category: "messaging",
    width: 900,
    height: 1200,
    aspectRatio: "3:4",
    description: "Recommended dimensions for WeChat Moments images (approx.)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "2MB",
  },
  {
    id: "line-timeline",
    name: "LINE Timeline Image",
    platform: "LINE",
    category: "messaging",
    width: 800,
    height: 1200,
    aspectRatio: "2:3",
    description: "Timeline and sticker preview sizes for LINE (recommended)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "2MB",
  },
  {
    id: "signal-image",
    name: "Signal Image",
    platform: "Signal",
    category: "messaging",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    description: "Square image optimized for Signal messages",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "8MB",
  },

  // Video & Streaming Platforms
  {
    id: "youtube-banner",
    name: "YouTube Channel Banner",
    platform: "YouTube",
    category: "video",
    width: 2560,
    height: 1440,
    aspectRatio: "16:9",
    description: "Channel banner for YouTube (safe area 1546×423 centered)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "6MB",
    safeZone: { top: 509, bottom: 509, left: 507, right: 507 } // note: central safe area 1546×423; values are approximate margins
  },
  {
    id: "vimeo-thumbnail",
    name: "Vimeo Thumbnail",
    platform: "Vimeo",
    category: "video",
    width: 1280,
    height: 720,
    aspectRatio: "16:9",
    description: "Thumbnail for Vimeo videos",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "youtube-shorts",
    name: "YouTube Shorts",
    platform: "YouTube",
    category: "video",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical video for YouTube Shorts",
    fileTypes: ["MP4", "MOV"],
    maxFileSize: "2GB",
  },
  {
    id: "twitch-banner",
    name: "Twitch Profile Banner",
    platform: "Twitch",
    category: "streaming",
    width: 1200,
    height: 480,
    aspectRatio: "5:2",
    description: "Channel header/banner for Twitch (standard size)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "twitch-profile",
    name: "Twitch Profile Picture",
    platform: "Twitch",
    category: "streaming",
    width: 800,
    height: 800,
    aspectRatio: "1:1",
    description: "Square avatar/profile picture for Twitch",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "2MB",
  },

  // Social networks we added
  {
    id: "snapchat-story",
    name: "Snapchat Story / Ad",
    platform: "Snapchat",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Full-screen vertical content for Snapchat Stories & Ads",
    fileTypes: ["JPG", "PNG", "MP4", "MOV"],
    maxFileSize: "5MB",
  },
  {
    id: "pinterest-pin",
    name: "Pinterest Pin (standard)",
    platform: "Pinterest",
    category: "social-media",
    width: 1000,
    height: 1500,
    aspectRatio: "2:3",
    description: "Recommended vertical pin size for Pinterest",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "10MB",
  },
  {
    id: "pinterest-square",
    name: "Pinterest Square Pin / Board Cover",
    platform: "Pinterest",
    category: "social-media",
    width: 600,
    height: 600,
    aspectRatio: "1:1",
    description: "Square pin or board cover for Pinterest",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "threads-post",
    name: "Threads Post Image",
    platform: "Threads",
    category: "social-media",
    width: 1440,
    height: 1920,
    aspectRatio: "3:4",
    description: "Recommended dimensions for Threads vertical images",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "8MB",
  },
  {
    id: "bereal-photo",
    name: "BeReal Photo",
    platform: "BeReal",
    category: "social-media",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    description: "Square photo size often used for BeReal posts",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "6MB",
  },
  {
    id: "bluesky-image",
    name: "Bluesky Post Image",
    platform: "Bluesky",
    category: "social-media",
    width: 1200,
    height: 780,
    aspectRatio: "15:9",
    description: "Common recommended width for Bluesky images (flexible)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "8MB",
  },

  // Advertising formats (Google / Meta / common ad sizes)
  {
    id: "google-ads-leaderboard",
    name: "Google Ads Leaderboard",
    platform: "Google Ads",
    category: "advertising",
    width: 728,
    height: 90,
    aspectRatio: "8.09:1",
    description: "Leaderboard banner, common desktop ad",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "google-ads-medium-rectangle",
    name: "Google Display - Medium Rectangle",
    platform: "Google Ads",
    category: "advertising",
    width: 300,
    height: 250,
    aspectRatio: "1.2:1",
    description: "Medium rectangle display ad (300×250)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "google-ads-large-rectangle",
    name: "Google Display - Large Rectangle",
    platform: "Google Ads",
    category: "advertising",
    width: 336,
    height: 280,
    aspectRatio: "1.2:1",
    description: "Large rectangle display ad (336×280)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "google-ads-mobile-banner",
    name: "Google Display - Mobile Banner",
    platform: "Google Ads",
    category: "advertising",
    width: 320,
    height: 50,
    aspectRatio: "6.4:1",
    description: "Mobile banner ad (320×50)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "google-ads-skyscraper",
    name: "Google Display - Wide Skyscraper",
    platform: "Google Ads",
    category: "advertising",
    width: 160,
    height: 600,
    aspectRatio: "0.27:1",
    description: "Wide skyscraper ad (160×600)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "facebook-ads-image",
    name: "Facebook Ads Image (single)",
    platform: "Facebook Ads",
    category: "advertising",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    description: "Single image ad for Facebook & Instagram feed",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "30MB",
  },
  {
    id: "instagram-ads-story",
    name: "Instagram Story Ad",
    platform: "Instagram Ads",
    category: "advertising",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Full-screen vertical ad for Instagram Stories",
    fileTypes: ["JPG", "PNG", "MP4"],
    maxFileSize: "4GB",
  },
  {
    id: "linkedin-ads-single",
    name: "LinkedIn Single Image Ad",
    platform: "LinkedIn Ads",
    category: "advertising",
    width: 1200,
    height: 627,
    aspectRatio: "1.91:1",
    description: "Single image ad for LinkedIn campaigns",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "google-responsive-display",
    name: "Google Responsive Display - Asset (recommended)",
    platform: "Google Ads",
    category: "advertising",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    description: "Suggested asset size for responsive display ads; Google will crop/resize as needed",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "facebook-carousel-image",
    name: "Facebook/Instagram Carousel Card",
    platform: "Meta Carousel",
    category: "advertising",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    description: "Single card for carousel ads (square is commonly used)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "30MB",
  },
  {
    id: "tiktok-spark-ad",
    name: "TikTok Spark Ad (post creative)",
    platform: "TikTok Ads",
    category: "advertising",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Native vertical ad format (Spark ads use organic posts as creative)",
    fileTypes: ["MP4", "MOV"],
    maxFileSize: "500MB",
  },

  // E-commerce product images (expanded)
  {
    id: "amazon-product",
    name: "Amazon Product Image (main)",
    platform: "Amazon",
    category: "ecommerce",
    width: 2000,
    height: 2000,
    aspectRatio: "1:1",
    description: "Square product image for Amazon listings (white background recommended)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "10MB",
  },
  {
    id: "shopify-product",
    name: "Shopify Product Image (recommended)",
    platform: "Shopify",
    category: "ecommerce",
    width: 2048,
    height: 2048,
    aspectRatio: "1:1",
    description: "High-resolution product image for Shopify stores",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "20MB",
  },
  {
    id: "etsy-listing",
    name: "Etsy Listing Image",
    platform: "Etsy",
    category: "ecommerce",
    width: 2000,
    height: 2000,
    aspectRatio: "1:1",
    description: "Square listing image for Etsy (use largest allowed for zoom)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "20MB",
  },
  {
    id: "ebay-gallery",
    name: "eBay Gallery Image",
    platform: "eBay",
    category: "ecommerce",
    width: 1600,
    height: 1600,
    aspectRatio: "1:1",
    description: "eBay gallery image size for product listings",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "12MB",
  },

  // Print & Document sizes (expanded)
  {
    id: "a4-document",
    name: "A4 Document",
    platform: "Print",
    category: "print",
    width: 2480,
    height: 3508,
    aspectRatio: "1:1.41",
    description: "Standard A4 document at 300 DPI (2480×3508 px)",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "25MB",
  },
  {
    id: "letter-document",
    name: "US Letter Document",
    platform: "Print",
    category: "print",
    width: 2550,
    height: 3300,
    aspectRatio: "1:1.29",
    description: "US Letter size at 300 DPI (8.5×11 in = 2550×3300 px)",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "25MB",
  },
  {
    id: "legal-document",
    name: "US Legal Document",
    platform: "Print",
    category: "print",
    width: 2550,
    height: 4200,
    aspectRatio: "1:1.65",
    description: "US Legal size at 300 DPI (8.5×14 in = 2550×4200 px)",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "30MB",
  },
  {
    id: "business-card",
    name: "Business Card (standard)",
    platform: "Print",
    category: "print",
    width: 1050,
    height: 600,
    aspectRatio: "1.75:1",
    description: "Standard business card at 300 DPI (3.5×2 in with bleed included in design tool)",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "10MB",
    safeZone: { top: 36, bottom: 36, left: 36, right: 36 },
  },
  {
    id: "poster-a3",
    name: "A3 Poster",
    platform: "Print",
    category: "print",
    width: 3508,
    height: 4961,
    aspectRatio: "1:1.41",
    description: "A3 print at 300 DPI",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "50MB",
  },
  {
    id: "cd-cover",
    name: "CD Cover / Jewel Case Insert",
    platform: "Print",
    category: "print",
    width: 1400,
    height: 1400,
    aspectRatio: "1:1",
    description: "Square cover art for CDs (design at 300 DPI)",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "20MB",
  },
  {
    id: "paperback-book-cover",
    name: "Paperback Book Cover (full spread)",
    platform: "Print",
    category: "print",
    width: 6000,
    height: 4000,
    aspectRatio: "3:2",
    description: "Full cover spread size depends on page count and bleed; example high-res template",
    fileTypes: ["PDF", "JPG", "PNG", "TIFF"],
    maxFileSize: "100MB",
  },
  {
    id: "flyer-a5",
    name: "Flyer A5",
    platform: "Print",
    category: "print",
    width: 1748,
    height: 2480,
    aspectRatio: "1:1.41",
    description: "A5 flyer at 300 DPI",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "30MB",
  },
  {
    id: "poster-a2",
    name: "Poster A2",
    platform: "Print",
    category: "print",
    width: 4961,
    height: 7016,
    aspectRatio: "1:1.41",
    description: "A2 print at 300 DPI",
    fileTypes: ["PDF", "JPG", "PNG", "TIFF"],
    maxFileSize: "150MB",
  },
  {
    id: "presentation-slide",
    name: "Presentation Slide (16:9)",
    platform: "PowerPoint/Keynote",
    category: "documents",
    width: 1920,
    height: 1080,
    aspectRatio: "16:9",
    description: "Standard slide size for PowerPoint/Keynote (export friendly)",
    fileTypes: ["PPTX", "PDF", "JPG", "PNG"],
    maxFileSize: "50MB",
  },

  // Community & Publishing Platforms
  {
    id: "reddit-banner",
    name: "Reddit Community Banner",
    platform: "Reddit",
    category: "community",
    width: 1920,
    height: 384,
    aspectRatio: "5:1",
    description: "Banner for Reddit communities",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "500KB",
  },
  {
    id: "reddit-profile",
    name: "Reddit Profile Picture",
    platform: "Reddit",
    category: "community",
    width: 256,
    height: 256,
    aspectRatio: "1:1",
    description: "Profile avatar for Reddit",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "100KB",
  },
  {
    id: "medium-header",
    name: "Medium Article Header / Featured Image",
    platform: "Medium",
    category: "community",
    width: 1400,
    height: 933,
    aspectRatio: "3:2",
    description: "Header image for Medium articles (featured image)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "25MB",
  },
  {
    id: "substack-header",
    name: "Substack Header",
    platform: "Substack",
    category: "community",
    width: 1456,
    height: 728,
    aspectRatio: "2:1",
    description: "Header image for Substack newsletters",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "behance-cover",
    name: "Behance Project Cover",
    platform: "Behance",
    category: "community",
    width: 1400,
    height: 600,
    aspectRatio: "7:3",
    description: "Project cover or hero image for Behance",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "20MB",
  },
  {
    id: "dribbble-shot",
    name: "Dribbble Shot",
    platform: "Dribbble",
    category: "community",
    width: 1600,
    height: 1200,
    aspectRatio: "4:3",
    description: "Standard showcase shot size for Dribbble (high-res recommended)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "20MB",
  },
  {
    id: "notion-cover",
    name: "Notion Page Cover",
    platform: "Notion",
    category: "documents",
    width: 1500,
    height: 600,
    aspectRatio: "2.5:1",
    description: "Page cover recommended width for Notion (flexible height)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },

  // Developer & Code Hosting (expanded)
  {
    id: "github-social",
    name: "GitHub Social Preview",
    platform: "GitHub",
    category: "developer",
    width: 1280,
    height: 640,
    aspectRatio: "2:1",
    description: "Social preview image for GitHub repositories",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "1MB",
  },
  {
    id: "gitlab-avatar",
    name: "GitLab Project Avatar",
    platform: "GitLab",
    category: "developer",
    width: 400,
    height: 400,
    aspectRatio: "1:1",
    description: "Square avatar for GitLab projects",
    fileTypes: ["JPG", "PNG", "SVG"],
    maxFileSize: "200KB",
  },
  {
    id: "stackoverflow-image",
    name: "Stack Overflow Post Image",
    platform: "Stack Overflow",
    category: "developer",
    width: 630,
    height: 500,
    aspectRatio: "1.26:1",
    description: "Image format for Stack Overflow posts / Q&A previews",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "2MB",
  },

  // App store assets
  {
    id: "appstore-icon",
    name: "App Store Icon (Apple)",
    platform: "Apple App Store",
    category: "apps",
    width: 1024,
    height: 1024,
    aspectRatio: "1:1",
    description: "App icon for Apple App Store (use layered/vector in source; upload PNG)",
    fileTypes: ["PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "playstore-icon",
    name: "Google Play Store Icon",
    platform: "Google Play",
    category: "apps",
    width: 512,
    height: 512,
    aspectRatio: "1:1",
    description: "Icon for Google Play (PNG recommended)",
    fileTypes: ["PNG"],
    maxFileSize: "1024KB",
  },
  {
    id: "appstore-screenshot",
    name: "App Store Screenshot (iPhone)",
    platform: "Apple App Store",
    category: "apps",
    width: 1242,
    height: 2688,
    aspectRatio: "9:20",
    description: "iPhone screenshot example (multiple sizes supported; high-res recommended)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "playstore-screenshot",
    name: "Google Play Screenshot",
    platform: "Google Play",
    category: "apps",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Portrait screenshot used on Google Play Store listing",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },

  // Audio / Podcast
  {
    id: "podcast-cover",
    name: "Podcast Cover Art",
    platform: "Podcast",
    category: "audio/podcast",
    width: 3000,
    height: 3000,
    aspectRatio: "1:1",
    description: "High-res podcast cover art (square). Many platforms accept 1400–3000 px; 3000×3000 recommended for future-proofing.",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "512KB",
  },

  // Email & Newsletters
  {
    id: "email-header",
    name: "Email Header / Hero",
    platform: "Email (generic)",
    category: "email",
    width: 600,
    height: 200,
    aspectRatio: "3:1",
    description: "Common email template header width (600px is de facto standard for many templates)",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "200KB",
  },
  {
    id: "newsletter-thumbnail",
    name: "Newsletter Featured Image",
    platform: "Email / Newsletter",
    category: "email",
    width: 1200,
    height: 600,
    aspectRatio: "2:1",
    description: "Featured image used in newsletter templates or email social previews",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "300KB",
  },

  // Documents & Templates (Canva/Google/Resume)
  {
    id: "google-doc-cover",
    name: "Google Docs Cover Image",
    platform: "Google Docs",
    category: "documents",
    width: 1200,
    height: 600,
    aspectRatio: "2:1",
    description: "Cover/header used in Google Docs templates",
    fileTypes: ["JPG", "PNG", "PDF"],
    maxFileSize: "10MB",
  },
  {
    id: "canva-instagram-template",
    name: "Canva Instagram Template (1080×1080)",
    platform: "Canva",
    category: "templates",
    width: 1080,
    height: 1080,
    aspectRatio: "1:1",
    description: "Common Canva template size for social posts",
    fileTypes: ["PNG", "JPG", "PDF"],
    maxFileSize: "50MB",
  },
  {
    id: "resume-a4",
    name: "Resume (A4)",
    platform: "Documents",
    category: "documents",
    width: 2480,
    height: 3508,
    aspectRatio: "1:1.41",
    description: "A4 resume layout at 300 DPI (easy to print & upload)",
    fileTypes: ["PDF", "DOCX"],
    maxFileSize: "5MB",
  },
  {
    id: "resume-letter",
    name: "Resume (US Letter)",
    platform: "Documents",
    category: "documents",
    width: 2550,
    height: 3300,
    aspectRatio: "1:1.29",
    description: "US Letter resume at 300 DPI",
    fileTypes: ["PDF", "DOCX"],
    maxFileSize: "5MB",
  },

  // Community extras & article images
  {
    id: "wordpress-featured",
    name: "WordPress / Blog Featured Image",
    platform: "WordPress",
    category: "community",
    width: 1200,
    height: 675,
    aspectRatio: "16:9",
    description: "Common blog featured image (flexible; many themes prefer 1200×675 or 1200×628)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "5MB",
  },

  // More social assets (headers & cover photos)
  {
    id: "facebook-cover",
    name: "Facebook Cover Photo",
    platform: "Facebook",
    category: "social-media",
    width: 820,
    height: 312,
    aspectRatio: "2.63:1",
    description: "Facebook page cover photo (desktop view). Keep key content centered.",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "100KB",
  },
  {
    id: "twitter-header",
    name: "Twitter / X Header",
    platform: "Twitter/X",
    category: "social-media",
    width: 1500,
    height: 500,
    aspectRatio: "3:1",
    description: "Profile header image for Twitter/X",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "linkedin-background",
    name: "LinkedIn Background / Cover",
    platform: "LinkedIn",
    category: "social-media",
    width: 1584,
    height: 396,
    aspectRatio: "4:1",
    description: "Background image for LinkedIn profile",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "8MB",
  },

  // Ads: YouTube & video ad specifics
  {
    id: "youtube-instream-16-9",
    name: "YouTube In-Stream Ad (16:9)",
    platform: "YouTube Ads",
    category: "advertising",
    width: 1280,
    height: 720,
    aspectRatio: "16:9",
    description: "Landscape in-stream ad video (16:9 standard)",
    fileTypes: ["MP4", "MOV"],
    maxFileSize: "1GB",
  },
  {
    id: "youtube-vertical-ad",
    name: "YouTube Vertical Ad (9:16)",
    platform: "YouTube Ads",
    category: "advertising",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical ad creative (for Shorts or vertical placements)",
    fileTypes: ["MP4", "MOV"],
    maxFileSize: "1GB",
  },

  // Messaging/community thumbnails & icons (expanded)
  {
    id: "slack-icon",
    name: "Slack Workspace Icon",
    platform: "Slack",
    category: "messaging",
    width: 512,
    height: 512,
    aspectRatio: "1:1",
    description: "Workspace icon/avatar for Slack",
    fileTypes: ["PNG", "JPG"],
    maxFileSize: "1MB",
  },

  // Misc social video/image types
  {
    id: "linkedin-article-image",
    name: "LinkedIn Article Hero Image",
    platform: "LinkedIn",
    category: "community",
    width: 744,
    height: 400,
    aspectRatio: "1.86:1",
    description: "Hero image for LinkedIn articles",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },

  // More ad and display sizes for comprehensiveness
  {
    id: "display-468x60",
    name: "Display - Banner (468×60)",
    platform: "Display Ads",
    category: "advertising",
    width: 468,
    height: 60,
    aspectRatio: "7.8:1",
    description: "Classic website banner",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "display-300x600",
    name: "Display - Half Page (300×600)",
    platform: "Display Ads",
    category: "advertising",
    width: 300,
    height: 600,
    aspectRatio: "1:2",
    description: "Tall half-page desktop ad",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "150KB",
  },
  {
    id: "display-970x250",
    name: "Display - Billboard (970×250)",
    platform: "Display Ads",
    category: "advertising",
    width: 970,
    height: 250,
    aspectRatio: "3.88:1",
    description: "Large billboard ad for high-impact placements",
    fileTypes: ["JPG", "PNG", "GIF"],
    maxFileSize: "250KB",
  },

  // Platform profile images and avatars (more)
  {
    id: "instagram-profile",
    name: "Instagram Profile Picture",
    platform: "Instagram",
    category: "social-media",
    width: 320,
    height: 320,
    aspectRatio: "1:1",
    description: "Profile image for Instagram (display cropped to circle)",
    fileTypes: ["JPG", "PNG", "WEBP"],
    maxFileSize: "10MB",
  },
  {
    id: "facebook-profile",
    name: "Facebook Profile Picture",
    platform: "Facebook",
    category: "social-media",
    width: 360,
    height: 360,
    aspectRatio: "1:1",
    description: "Profile image for Facebook (display cropped to circle)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },
  {
    id: "linkedin-profile",
    name: "LinkedIn Profile Photo",
    platform: "LinkedIn",
    category: "social-media",
    width: 400,
    height: 400,
    aspectRatio: "1:1",
    description: "LinkedIn profile photo recommended square size",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "8MB",
  },

  // Stories & ephemeral content specifics to more platforms
  {
    id: "facebook-story",
    name: "Facebook Story",
    platform: "Facebook",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Full-screen vertical content for Facebook Stories",
    fileTypes: ["JPG", "PNG", "MP4"],
    maxFileSize: "4GB",
  },
  {
    id: "snapchat-geofilter",
    name: "Snapchat Geofilter (overlay)",
    platform: "Snapchat",
    category: "social-media",
    width: 1080,
    height: 2340,
    aspectRatio: "1:2.16",
    description: "Design for Snapchat geofilters (overlay safe zones applied at upload)",
    fileTypes: ["PNG"],
    maxFileSize: "300KB",
  },

  // Other specialty & niche formats
  {
    id: "spotify-artist-banner",
    name: "Spotify Artist Banner (profile)",
    platform: "Spotify",
    category: "music",
    width: 2660,
    height: 1140,
    aspectRatio: "2.33:1",
    description: "Hero image used on artist profile and playlists (approx. sizes vary)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "50MB",
  },
  {
    id: "soundcloud-artwork",
    name: "SoundCloud Track Artwork",
    platform: "SoundCloud",
    category: "music",
    width: 1000,
    height: 1000,
    aspectRatio: "1:1",
    description: "Square artwork for tracks on SoundCloud",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },

  // More platform & ad coverage to reach wide variety
  {
    id: "ebay-thumbnail",
    name: "eBay Thumbnail (listing)",
    platform: "eBay",
    category: "ecommerce",
    width: 500,
    height: 500,
    aspectRatio: "1:1",
    description: "Thumbnail size used by eBay (storefront/listing previews)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "etsy-banner",
    name: "Etsy Shop Banner",
    platform: "Etsy",
    category: "ecommerce",
    width: 1200,
    height: 300,
    aspectRatio: "4:1",
    description: "Shop banner image for Etsy storefronts",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },

  // Photo & gallery formats
  {
    id: "portfolio-hero",
    name: "Portfolio Hero / Full Bleed",
    platform: "Portfolio",
    category: "photography",
    width: 3000,
    height: 2000,
    aspectRatio: "3:2",
    description: "Large hero image suitable for photography portfolios and hero sections",
    fileTypes: ["JPG", "PNG", "TIFF"],
    maxFileSize: "100MB",
  },

  // Misc - icons & thumbnails
  {
    id: "favicon",
    name: "Favicon",
    platform: "Web",
    category: "web",
    width: 48,
    height: 48,
    aspectRatio: "1:1",
    description: "Favicon/icon for websites (multiple sizes recommended: 16×16, 32×32, 48×48, 64×64 etc.)",
    fileTypes: ["ICO", "PNG", "SVG"],
    maxFileSize: "100KB",
  },

  // Expanded set of social ad creative sizes (to add count)
  {
    id: "instagram-reel-cover",
    name: "Instagram Reel Cover (vertical)",
    platform: "Instagram",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Cover image for Instagram Reels (also used as story-style visual)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "4GB",
  },
  {
    id: "tiktok-thumbnail",
    name: "TikTok Custom Thumbnail",
    platform: "TikTok",
    category: "social-media",
    width: 1080,
    height: 1920,
    aspectRatio: "9:16",
    description: "Vertical thumbnail used on TikTok (can be extracted from video or uploaded)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },

  // More community/developer thumbnails & large social items to expand library
  {
    id: "youtube-channel-icon",
    name: "YouTube Channel Icon",
    platform: "YouTube",
    category: "social-media",
    width: 800,
    height: 800,
    aspectRatio: "1:1",
    description: "YouTube channel avatar/profile image (displayed cropped to circle)",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "2MB",
  },
  {
    id: "patreon-cover",
    name: "Patreon Creator Cover",
    platform: "Patreon",
    category: "community",
    width: 1600,
    height: 400,
    aspectRatio: "4:1",
    description: "Header/cover image for Patreon creator page",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "10MB",
  },

  // Add some marketplace / design asset sizes
  {
    id: "canva-facebook-ad",
    name: "Canva Template - Facebook Ad (single)",
    platform: "Canva",
    category: "templates",
    width: 1200,
    height: 628,
    aspectRatio: "1.91:1",
    description: "Canva template size for Facebook/Instagram feed ads",
    fileTypes: ["PNG", "JPG", "PDF"],
    maxFileSize: "50MB",
  },

  // Final group (makes total broad and close to requested scale)
  {
    id: "google-my-business",
    name: "Google Business Profile - Cover",
    platform: "Google",
    category: "business",
    width: 1024,
    height: 576,
    aspectRatio: "16:9",
    description: "Cover image used on Google Business Profile listing",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "etsy-shop-icon",
    name: "Etsy Shop Icon",
    platform: "Etsy",
    category: "ecommerce",
    width: 500,
    height: 500,
    aspectRatio: "1:1",
    description: "Square icon for Etsy shop",
    fileTypes: ["JPG", "PNG"],
    maxFileSize: "5MB",
  },
  {
    id: "printable-invitation",
    name: "Invitation (5×7 in) Printable",
    platform: "Print",
    category: "print",
    width: 1500,
    height: 2100,
    aspectRatio: "1:1.4",
    description: "5×7 inch invitation at 300 DPI",
    fileTypes: ["PDF", "JPG", "PNG"],
    maxFileSize: "30MB",
  }
];

// Update category counts
categories.forEach((category) => {
  if (category.id === "all") {
    category.count = contentFormats.length
  } else {
    category.count = contentFormats.filter((format) => format.category === category.id).length
  }
})
